<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Destination;
use AppBundle\Entity\Hotel;
use Symfony\Component\HttpFoundation\Request;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends \Doctrine\ORM\EntityRepository
{

    public function findHotelsAction($destination)
    {
        $em=$this->getEntityManager();
        $hotel = $em->createQuery("SELECT h FROM AppBundle:Hotel h LEFT JOIN AppBundle:Destination d with h.destination = d.id WHERE d.destinationName = :destination")
        ->setParameter('destination', $destination);
        $result = $hotel->getResult();
        return $result;
    }

    public function findDestinationAction()
    {
        $em = $this->getEntityManager();
        $destinatonQuery = $em->createQuery('SELECT h FROM AppBundle:Destination h');
        $destinations = $destinatonQuery->getResult();
        foreach ($destinations as $destination)
        {
            if($destination instanceof Destination){
                $details[] = array(
                    'destinatonName' => $destination->getDestinationName()
                );
            }
        }
        return $details;
    }

    public function filterHotelAction()
    {
        $destination    = $_POST['destination'];
        list($price1,$price2) = explode(",",$_POST['price']);
        $em=$this->getEntityManager();
        $hotel = $em->createQuery("SELECT h FROM AppBundle:Hotel h LEFT JOIN AppBundle:Destination d with h.destination = d.id WHERE d.destinationName = :destination AND h.priceRangeA BETWEEN  $price1 AND $price2")
            ->setParameter('destination', $destination);
        $result = $hotel->getResult();
        return $result;
    }
}
