<?php

namespace AppBundle\Repository;

/**
 * MilestoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilestoneRepository extends \Doctrine\ORM\EntityRepository
{
}
